### ISSUE TITLE
Licencing Conflict

### ISSUE THREAD

**Issue by pennro-se** [jesseduffield/horcrux-ui#8]
As mentioned in [this reddit comment](https://www.reddit.com/r/crypto/comments/i2exys/jesseduffieldhorcruxui_split_a_file_into_horcruxes/g04hk7l/), the project here is licensed as [MIT](https://github.com/jesseduffield/horcrux-ui/blob/master/LICENSE) however the [Hashicorp Vault](https://github.com/hashicorp/vault) is [MPL-2.0](https://github.com/hashicorp/vault/blob/master/LICENSE).

**Comment by jesseduffield** [comment]
Looking at that license it seems like I should be fine to add a reference to the original license in the vault files themselves: https://softwareengineering.stackexchange.com/questions/317944/can-i-include-code-licensed-under-mpl-within-a-project-under-mit-license

**Comment by jesseduffield** [comment]
I've just pushed a commit d35f41a5 which bumps the version of horcrux to one that references the original license. Let me know if you think anything else needs doing :)
